car/urls.py
from django.urls import path
from car.views import create_car, show_car, contact, error_login, thanks, update_car, eliminate_car

urlpatterns = [
    path('create_car/', create_car),
    path('show_car/', show_car, name='show_car'),
    path('contact/', contact),
    path('error_login/', error_login),
    path('thanks/', thanks),
    path('update_car/<id>/', update_car, name='update_car'),
    path('eliminate_car/<id>/', eliminate_car, name='eliminate_car'),
    ]

proyecto_final/urls.py
from django.contrib import admin
from django.urls import path, include
from proyecto_final.views import index, about
from django.conf.urls.static import static
from proyecto_final.settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('about/', about),
    path('car/', include('car.urls')),
    path('users/', include('users.urls')),  
    path('accounts/', include('django.contrib.auth.urls')),  
]

urlpatterns+= static (MEDIA_URL, document_root = MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import login_view, register, update_user, update_user_profile, show_user, UserList, edit_user, edit_profile_user, eliminate_user

urlpatterns = [
    path('login/', login_view),
    path('logout/', LogoutView.as_view(template_name = 'users/logout.html')),
    path('register/', register),
    path('update/<id>/', update_user),
    path('update/profile/<id>', update_user_profile, name='update_profile'),
    path('show_user/', show_user),
    path('user_list/', UserList.as_view(), name='user_list'),
    path('edit_user/<id>/', edit_user),
    path('edit_profile/<id>/', edit_profile_user),
    path('eliminate_user/<id>/', eliminate_user),
]

car/models.py
from django.db import models

# Create your models here.
class Car(models.Model):
    name=models.CharField(max_length=50)
    plate=models.CharField(max_length=7)
    year=models.IntegerField()
    km=models.IntegerField(default=0)
    price=models.IntegerField()
    in_house = models.BooleanField(default=True)
    image = models.ImageField(upload_to='car_image', null=False)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.db.models.signals import post_save

# Create your models here.
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    phone = models.CharField(max_length=25, null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    profile_picture = models.ImageField(upload_to='profile_images', null=True, blank=True)

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from users.models import UserProfile
from django import forms




class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True, label='Nombre')
    last_name = forms.CharField(max_length=100, required=True, label='Apellido')
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        help_texts={k:"" for k in fields}

class UserUpdateForm(forms.ModelForm):
    username = forms.CharField(max_length=100, required=False, label='Nombre de usuario')
    first_name = forms.CharField(max_length=100, required=False, label='Nombre')
    last_name = forms.CharField(max_length=100, required=False, label='Apellido')
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name']


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'birth_date', 'profile_picture']

users/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView
from users.models import User
from users.forms import RegisterForm, UserUpdateForm, UserProfileForm
from django.contrib import messages
from users.mixins import LoginStaffMixin

def login_view(request):
    if request.method == 'GET':
        form = AuthenticationForm()
        context = {
            'form':form
        }
        return render(request, 'registration/login.html', context=context)
    
    elif request.method == 'POST':
        form = AuthenticationForm(request = request, data = request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                context = {
                    'message':f'Bienvenido {username}!!!'
                }
                return render(request, 'index.html', context=context)

        form = AuthenticationForm()
        context ={
            'form':form,
            'errors':'Usuario o contraseña incorrectos!'
        }
        return render(request, 'registration/login.html', context=context)

def register(request):
    data={
        'form': RegisterForm()
    }
    if request.method == 'POST':
        register_form=RegisterForm(data=request.POST)

        if register_form.is_valid():
            register_form.save()
            user= authenticate(username=register_form.cleaned_data['username'], password=register_form.cleaned_data['password1'])
            login(request, user)
            return redirect(to="/")
    else:
        register_form=RegisterForm()
    return render(request, 'users/register.html', data)


@login_required
def update_user(request,id):
    user = User.objects.get(id=id)
    if request.method == 'GET':
        form=UserUpdateForm(instance=user)
    else:
        form = UserUpdateForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Datos actualizados correctamente')
        return redirect(to ="/users/show_user/" )
    return render(request, 'users/update_user.html', {'form':form})


@login_required
def update_user_profile(request,id):
    user = User.objects.get(id=id)
    if request.method == 'GET':
        form = UserProfileForm(initial={
            'phone':request.user.profile.phone,
            'birth_date':request.user.profile.birth_date,
            'profile_picture':request.user.profile.profile_picture
        })
        context ={
            'form':form
        }
        return render(request, 'users/update_profile.html', context=context)   
    if request.method == 'GET':
        form=UserProfileForm(instance=user)
    else:
        form = UserProfileForm(request.POST, instance=user,  files=request.FILES)
        if form.is_valid():
            user.profile.phone = form.cleaned_data.get('phone')
            user.profile.birth_date = form.cleaned_data.get('birth_date')
            user.profile.profile_picture = form.cleaned_data.get('profile_picture')
            form.save()
            messages.success(request, 'Datos actualizados correctamente')
        return redirect(to ="/users/user_list/" )
    return render(request, 'users/update_profile.html', {'form':form})


@login_required
def show_user(request):

    return render(request, 'users/show_user.html')


class UserList(LoginStaffMixin,ListView):

    model=User
    template_name= 'users/user_list.html'
    permission_required='perms.app.delete_user'

    def get_queryset(self):
        return self.model.objects.filter(is_active=True)

@permission_required('auth.change_user')
def edit_user(request,id):
    user = User.objects.get(id=id)
    if request.method == 'GET':
        form=UserUpdateForm(instance=user)
    else:
        form = UserUpdateForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Datos actualizados correctamente')
        return redirect(to ="/users/user_list/" )
    return render(request, 'users/update_user.html', {'form':form})

@permission_required('users.change_userprofile')
def edit_profile_user(request,id):
    user = User.objects.get(id=id)
    if request.method == 'GET':
        form = UserProfileForm(initial={
            'phone':request.user.profile.phone,
            'birth_date':request.user.profile.birth_date,
            'profile_picture':request.user.profile.profile_picture
        })
        context ={
            'form':form
        }
        return render(request, 'users/update_profile.html', context=context)   
    if request.method == 'GET':
        form=UserProfileForm(instance=user)
    else:
        form = UserProfileForm(request.POST, instance=user,  files=request.FILES)
        if form.is_valid():
            user.profile.phone = form.cleaned_data.get('phone')
            user.profile.birth_date = form.cleaned_data.get('birth_date')
            user.profile.profile_picture = form.cleaned_data.get('profile_picture')
            form.save()
            messages.success(request, 'Datos actualizados correctamente')
        return redirect(to ="/users/user_list/" )
    return render(request, 'users/update_profile.html', {'form':form})


@permission_required('auth.delete_user')
def eliminate_user(request, id):
    user = get_object_or_404(User, id=id)
    user.delete()
    messages.success(request, 'Usuario eliminado')
    return redirect(to="/users/user_list/")

templates/users/logout.html
{% extends 'base.html' %}

{% block title %}
    Logout
{% endblock %}

{% block content %}
{% load static %}
<div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        
        <div class="col mb-5">
            <div class="card h-100">
                <!-- Product image-->
                <img class="card-img-top" src="{% static 'assets/comeback.png' %}" alt="..." />
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <h5 class="fw-bolder">Gracias, vuelva pronto!</h5>            
                    </div>
                </div>
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href='/users/login/'>Ingresar</a></div>
                </div>
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href='/car/show_car/'>Volver</a></div>
                </div>
            </div>
        </div>

        
    </div>
</div>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}

{% block title %}
    Registro
{% endblock %}

{% block content %}
{% load static %}
<!-- Google fonts-->
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
<link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
<!-- Core theme CSS (includes Bootstrap)-->
<link href="{% static 'css/styles2.css' %}" rel="stylesheet" />

<div class="container">
    <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Completa el formulario para registrarte</h2>
    <!-- Icon Divider-->
    <div class="divider-custom">
        <div class="divider-custom-line"></div>
    </div>
    <div class="row justify-content-center">
        <div class="row justify-content-center">
            {% if form %}
                
                <div class="col-lg-8 col-xl-7">
                    <form action="" method="POST" enctype="multipart/form-data" >

                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            <table>
                                {{form.as_table}}
                            </table>
                        </div>
                        <input type="submit" value="Registrarse">
                    </form>
                </div>
            {% endif %}
            {% if errors %}
                {{errors}}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/users/show_user.html
{% extends 'base.html' %}



{% block title %}
    Datos personales
{% endblock %}

{% block content %}
{% load static %}
    <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Mis Datos</h2>
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                <div class="col mb-5">
                    <div class="card h-100">
                        {% if request.user.profile.profile_picture.url is not null%}
                        <!-- User image-->
                        <img class="card-img-top" src="{{request.user.profile.profile_picture.url}}" alt="..." />
                        {%else%}
                        <!-- User image default-->
                        <img class="card-img-top" src="{% static 'assets/user_default.png' %}" alt="..." />
                        {%endif%}
                        <!-- User details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product username-->
                                <h3 class="fw-bolder">{{request.user.first_name}}</h3><h3 class="fw-bolder">{{request.user.last_name}}</h3>
                                <!-- Product Full name-->
                                <h5 class="fw-bolder">{{request.user.username}}</h5>                                
                                <!-- User phone-->
                                <p>{{request.user.profile.phone}}</p>
                                <!-- User email-->
                                <p>{{request.user.email}}</p>
                                <!-- User date-->
                                <p>{{request.user.profile.birth_date}}</p>        
                            </div>
                        </div>
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-info btn-sm" href="/users/update/{{user.id}}">Actualizar datos personales</a></div>
                        </div>
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-info btn-sm" href="/users/update/profile/{{user.id}}">Actualizar perfil</a></div>
                        </div>
                    </div>
                </div>
            </div>
            {% if perms.app.add_car %}
            <h2>Añadir un vehículo </h2> <a href="/car/create_car/" class="btn btn-primary">Crear</a>
            {% endif %}
        </div>
    </section>

{% endblock %}

templates/users/update_profile.html
{% extends 'base.html' %}

{% block title %}
    Actualización
{% endblock %}

{% block content %}
{% load static %}
<!-- Google fonts-->
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
<link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
<!-- Core theme CSS (includes Bootstrap)-->
<link href="{% static 'css/styles2.css' %}" rel="stylesheet" />

<div class="container">
    <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Actualizar perfil</h2>
    <!-- Icon Divider-->
    <div class="divider-custom">
        <div class="divider-custom-line"></div>
    </div>
    <div class="row justify-content-center">
        <div class="row justify-content-center">
            {% if form %}
                
                <div class="col-lg-8 col-xl-7">
                    <form action="" method="POST" enctype="multipart/form-data" >

                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            <table>
                                {{form.as_table}}
                            </table>
                        </div>
                        <input type="submit" value="Actualizar">
                    </form>
                </div>
            {% endif %}
            {% if errors %}
                {{errors}}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/users/update_user.html
{% extends 'base.html' %}

{% block title %}
    Actualización
{% endblock %}

{% block content %}
{% load static %}
<!-- Google fonts-->
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
<link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
<!-- Core theme CSS (includes Bootstrap)-->
<link href="{% static 'css/styles2.css' %}" rel="stylesheet" />

<div class="container">
    <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Actualizar usuario</h2>
    <!-- Icon Divider-->
    <div class="divider-custom">
        <div class="divider-custom-line"></div>
    </div>
    <div class="row justify-content-center">
        <div class="row justify-content-center">
            {% if form %}
                
                <div class="col-lg-8 col-xl-7">
                    <form action="" method="POST" enctype="multipart/form-data" >

                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            <table>
                                {{form.as_table}}
                            </table>
                        </div>
                        <input type="submit" value="Actualizar">
                    </form>
                </div>
            {% endif %}
            {% if errors %}
                {{errors}}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/users/user_list.html
{% extends 'base.html' %}



{% block title %}
    Lista de usuarios
{% endblock %}

{% block content %}
{% if object_list%}
<div class="card">
    <div class="card-header">
        <strong class="card-title">Listado de usuarios</strong>
    </div>
    <div class="table-stats order-table ov-h">
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Username</th>
                    <th>Name</th>
                    <th>Last name</th>
                    <th>Birth Date</th>
                </tr>
            </thead>
            <tbody>
                {% for user in object_list %}
                <tr>
                    <td>{{user.id}}</td>
                    <td>{{user.username}}</td>
                    <td>{{user.first_name}}</td>
                    <td>{{user.last_name}}</td>
                    <td>{{user.profile.birth_date}}</td>
                    <td>
                        <a href='/users/edit_user/{{user.id}}' class="btn btn-primary">Actualizar Datos</a>
                        <a href="/users/edit_profile/{{user.id}}" class="btn btn-primary">Actualizar Perfil</a>
                        <a href="/users/eliminate_user/{{user.id}} " class="btn btn-danger">Eliminar</a>
                    </td>
                </tr>
                {%endfor%}
            </tbody>
        </table>
    </div>
{%else%}
<h1>No existen usuarios registrados</h1>   
</div>
{%endif%}
{% endblock %}